export const GET_CARDS_LIST = 'GET_CARDS_LIST_REQUEST';
export const GET_CARDS_LIST_SUCCESS = 'GET_CARDS_LIST_SUCCESS';
export const GET_CARDS_LIST_FAIL = 'GET_CARDS_LIST_FAIL';
export const SET_SEARCH_TAG = 'SET_SEARCH_TAG';
